<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => '1',
                'category_id' => '3',
                'name' => 'Dignissimos quia quos.',
                'image_url' => 'https://lorempixel.com/400/400/?92484',
                'description' => 'Recusandae illo nam error et iusto eos sed. Autem amet explicabo reiciendis rerum ea est est. Asperiores perspiciatis aut harum quam aut ut quod. Molestias est ut in sed.',
                'price' => '226',
                'offer' => '0',
                'offer_price' => '0',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:31',
                'updated_at' => '2020-06-16 17:51:31',
            ),
            1 => 
            array (
                'id' => '2',
                'category_id' => '3',
                'name' => 'Quo nobis culpa ut.',
                'image_url' => 'https://lorempixel.com/400/400/?13978',
                'description' => 'Repellat non recusandae beatae. Voluptate quod hic illum ad non. Ducimus sit autem soluta architecto. Sequi fuga dolor et.',
                'price' => '78',
                'offer' => '0',
                'offer_price' => '5',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:31',
                'updated_at' => '2020-06-16 17:51:31',
            ),
            2 => 
            array (
                'id' => '3',
                'category_id' => '5',
                'name' => 'Perferendis distinctio enim.',
                'image_url' => 'https://lorempixel.com/400/400/?29443',
                'description' => 'Error perferendis voluptates odit et. Aspernatur alias quaerat alias expedita voluptates. Delectus explicabo at eius molestiae et. Eligendi beatae voluptatum sint. Eaque non quo nam veritatis assumenda ratione.',
                'price' => '588',
                'offer' => '0',
                'offer_price' => '8',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:31',
                'updated_at' => '2020-06-16 17:51:31',
            ),
            3 => 
            array (
                'id' => '4',
                'category_id' => '2',
                'name' => 'Vel possimus explicabo.',
                'image_url' => 'https://lorempixel.com/400/400/?42797',
                'description' => 'Quam optio laborum cumque praesentium natus aut. In tempore beatae dolores eaque quis aliquam sunt ratione. Sapiente qui quos est autem aut repudiandae adipisci. Ea nihil recusandae est eos at.',
                'price' => '525',
                'offer' => '0',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            4 => 
            array (
                'id' => '5',
                'category_id' => '5',
                'name' => 'Mollitia autem id ea.',
                'image_url' => 'https://lorempixel.com/400/400/?49275',
                'description' => 'Dolorem occaecati rerum quia sed esse quibusdam. Excepturi excepturi et vitae ducimus. Laborum cumque porro vel consequatur vel doloremque. Illum fugit quaerat reprehenderit enim sit quisquam doloribus.',
                'price' => '233',
                'offer' => '1',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            5 => 
            array (
                'id' => '6',
                'category_id' => '5',
                'name' => 'Veniam est nam.',
                'image_url' => 'https://lorempixel.com/400/400/?64655',
                'description' => 'Et velit veritatis corrupti quidem non. Sint voluptas consequatur similique est corrupti a rerum. Vero aperiam consequatur voluptas dolor. Qui corporis aut sint.',
                'price' => '612',
                'offer' => '0',
                'offer_price' => '0',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            6 => 
            array (
                'id' => '7',
                'category_id' => '1',
                'name' => 'Magnam alias dolores at.',
                'image_url' => 'https://lorempixel.com/400/400/?73420',
                'description' => 'Esse sed odit quae sapiente. Deserunt in dolorem aut sapiente eaque est. Autem reiciendis eligendi quaerat. Ad laboriosam consequatur quam dolores omnis.',
                'price' => '978',
                'offer' => '0',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            7 => 
            array (
                'id' => '8',
                'category_id' => '1',
                'name' => 'Sunt fugiat maxime molestiae.',
                'image_url' => 'https://lorempixel.com/400/400/?84316',
                'description' => 'Minus aliquid nobis nihil. Ut soluta reprehenderit repudiandae omnis facilis eligendi error. Rerum quis omnis enim temporibus vel.',
                'price' => '295',
                'offer' => '1',
                'offer_price' => '8',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            8 => 
            array (
                'id' => '9',
                'category_id' => '2',
                'name' => 'Quia tempora laboriosam.',
                'image_url' => 'https://lorempixel.com/400/400/?89726',
                'description' => 'Molestiae ut culpa ut illo ut et est. Et eos error unde quisquam. Reiciendis aperiam autem numquam laborum inventore. Animi illum placeat officia autem sit eum.',
                'price' => '990',
                'offer' => '0',
                'offer_price' => '0',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            9 => 
            array (
                'id' => '10',
                'category_id' => '3',
                'name' => 'Dolor maiores mollitia quasi.',
                'image_url' => 'https://lorempixel.com/400/400/?69533',
                'description' => 'Sed neque nisi alias aut quibusdam ab. Pariatur aspernatur suscipit enim ut. Veritatis expedita esse quia dolorem. Iusto voluptates qui sed in porro sit est.',
                'price' => '162',
                'offer' => '0',
                'offer_price' => '7',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:32',
                'updated_at' => '2020-06-16 17:51:32',
            ),
            10 => 
            array (
                'id' => '11',
                'category_id' => '1',
                'name' => 'Nam deserunt aut.',
                'image_url' => 'https://lorempixel.com/400/400/?51787',
                'description' => 'Maxime error nulla ab. Vitae laborum eos voluptate autem officia ad temporibus. Hic molestiae veniam necessitatibus itaque maiores ea voluptas. Temporibus laboriosam at odit blanditiis vero similique qui.',
                'price' => '472',
                'offer' => '1',
                'offer_price' => '2',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            11 => 
            array (
                'id' => '12',
                'category_id' => '1',
                'name' => 'Aut et quasi.',
                'image_url' => 'https://lorempixel.com/400/400/?58684',
                'description' => 'Commodi consequatur dolor autem ab. Repellendus dolores et voluptate qui cum ad. Dolorum sint voluptate sed voluptas.',
                'price' => '415',
                'offer' => '0',
                'offer_price' => '5',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            12 => 
            array (
                'id' => '13',
                'category_id' => '3',
                'name' => 'Minima enim earum eaque.',
                'image_url' => 'https://lorempixel.com/400/400/?28060',
                'description' => 'Nisi aut molestiae quibusdam numquam non ut nulla. Aliquam et molestiae iure quia. Voluptatem eius placeat rerum. Voluptas voluptatem impedit voluptatem quas.',
                'price' => '691',
                'offer' => '0',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            13 => 
            array (
                'id' => '14',
                'category_id' => '5',
                'name' => 'Id error sunt.',
                'image_url' => 'https://lorempixel.com/400/400/?33057',
                'description' => 'Est et pariatur dolore ut temporibus quidem. Ab eum eveniet ipsa enim rerum ut. Magnam maiores aliquid explicabo cum debitis.',
                'price' => '865',
                'offer' => '0',
                'offer_price' => '6',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            14 => 
            array (
                'id' => '15',
                'category_id' => '5',
                'name' => 'Et tempore a et.',
                'image_url' => 'https://lorempixel.com/400/400/?79741',
                'description' => 'Ut nihil error eos. Ex fugit non autem voluptatem. Nisi temporibus quia ut accusantium consequatur. Ut molestiae blanditiis et consequatur.',
                'price' => '173',
                'offer' => '1',
                'offer_price' => '8',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            15 => 
            array (
                'id' => '16',
                'category_id' => '2',
                'name' => 'Nulla aut voluptas similique fuga.',
                'image_url' => 'https://lorempixel.com/400/400/?98290',
                'description' => 'Nostrum quia inventore dignissimos fugit animi expedita. Pariatur totam quod quisquam ut.',
                'price' => '252',
                'offer' => '0',
                'offer_price' => '4',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            16 => 
            array (
                'id' => '17',
                'category_id' => '2',
                'name' => 'Harum voluptas.',
                'image_url' => 'https://lorempixel.com/400/400/?43483',
                'description' => 'Maxime earum autem officia veritatis corrupti hic dolorum dolores. Rerum ipsa quos recusandae repellendus rerum. Tenetur ipsum quasi non. Delectus consequatur ratione ut at.',
                'price' => '616',
                'offer' => '0',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            17 => 
            array (
                'id' => '18',
                'category_id' => '5',
                'name' => 'Et necessitatibus quia et.',
                'image_url' => 'https://lorempixel.com/400/400/?70466',
                'description' => 'Voluptatem reiciendis dicta distinctio omnis nesciunt nobis repellendus. Dolor et exercitationem aperiam dolorum. In et praesentium et accusamus quos similique ratione. Repellat quis consequuntur qui ullam quia eaque quas. Debitis veniam possimus voluptatem distinctio qui ea est aliquid.',
                'price' => '29',
                'offer' => '0',
                'offer_price' => '7',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            18 => 
            array (
                'id' => '19',
                'category_id' => '1',
                'name' => 'Accusantium est.',
                'image_url' => 'https://lorempixel.com/400/400/?87382',
                'description' => 'Et a quae mollitia praesentium voluptatem itaque impedit. Recusandae et doloribus asperiores vitae. Quia architecto molestiae debitis accusamus sit. Et hic aut nihil fuga nihil.',
                'price' => '350',
                'offer' => '1',
                'offer_price' => '5',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            19 => 
            array (
                'id' => '20',
                'category_id' => '1',
                'name' => 'Non impedit asperiores aut.',
                'image_url' => 'https://lorempixel.com/400/400/?80515',
                'description' => 'Error quas nemo in numquam asperiores incidunt. Eveniet laudantium quod rem id provident cumque minima. Suscipit laborum enim neque incidunt. Ut atque architecto consequatur est temporibus fuga pariatur voluptas.',
                'price' => '119',
                'offer' => '0',
                'offer_price' => '6',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            20 => 
            array (
                'id' => '21',
                'category_id' => '3',
                'name' => 'Velit laborum quisquam laboriosam.',
                'image_url' => 'https://lorempixel.com/400/400/?50657',
                'description' => 'Est sed tempore at reiciendis. Quasi facilis et amet impedit. Et itaque at sint eum neque dicta iure. Placeat repudiandae blanditiis sint reprehenderit minus ea.',
                'price' => '615',
                'offer' => '0',
                'offer_price' => '8',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:33',
                'updated_at' => '2020-06-16 17:51:33',
            ),
            21 => 
            array (
                'id' => '22',
                'category_id' => '1',
                'name' => 'Sit quidem iusto.',
                'image_url' => 'https://lorempixel.com/400/400/?71383',
                'description' => 'Aliquam vel culpa mollitia est aut. Perferendis excepturi officia voluptates et. Recusandae velit dolores velit veritatis sed iste omnis.',
                'price' => '829',
                'offer' => '0',
                'offer_price' => '3',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            22 => 
            array (
                'id' => '23',
                'category_id' => '4',
                'name' => 'Non ullam.',
                'image_url' => 'https://lorempixel.com/400/400/?76049',
                'description' => 'Fugit rerum et et ipsa rerum accusantium optio. Vitae tempore et quos consequuntur iste.',
                'price' => '962',
                'offer' => '0',
                'offer_price' => '3',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            23 => 
            array (
                'id' => '24',
                'category_id' => '4',
                'name' => 'Ad consequatur magnam.',
                'image_url' => 'https://lorempixel.com/400/400/?54774',
                'description' => 'Ea ut facilis qui expedita. Pariatur inventore aut sunt non enim. Et vel velit quibusdam.',
                'price' => '10',
                'offer' => '0',
                'offer_price' => '9',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            24 => 
            array (
                'id' => '25',
                'category_id' => '4',
                'name' => 'Iste similique molestiae.',
                'image_url' => 'https://lorempixel.com/400/400/?35999',
                'description' => 'Quia autem eum excepturi ipsam. Omnis reiciendis harum provident minus dicta.',
                'price' => '854',
                'offer' => '0',
                'offer_price' => '4',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            25 => 
            array (
                'id' => '26',
                'category_id' => '3',
                'name' => 'Ut rerum dolores modi.',
                'image_url' => 'https://lorempixel.com/400/400/?68099',
                'description' => 'Eum veritatis incidunt esse nam et. Sint itaque consequatur veritatis quas. Aliquid voluptas reiciendis deserunt. Voluptatem ipsum autem adipisci inventore officia aut.',
                'price' => '380',
                'offer' => '0',
                'offer_price' => '8',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            26 => 
            array (
                'id' => '27',
                'category_id' => '2',
                'name' => 'Culpa magnam maxime necessitatibus.',
                'image_url' => 'https://lorempixel.com/400/400/?43426',
                'description' => 'Dicta similique iste at qui fuga error. Id commodi dolorum ipsam quia perferendis quo. Consequatur labore aliquam asperiores fugiat. Rerum qui ut quae et officiis quis.',
                'price' => '751',
                'offer' => '1',
                'offer_price' => '4',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            27 => 
            array (
                'id' => '28',
                'category_id' => '5',
                'name' => 'Deserunt quos ea et.',
                'image_url' => 'https://lorempixel.com/400/400/?47333',
                'description' => 'Sit dolorem voluptatem impedit deleniti provident aut perferendis. Perferendis est iure voluptatem ut. Sed voluptas deserunt officiis commodi debitis reiciendis.',
                'price' => '279',
                'offer' => '0',
                'offer_price' => '4',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            28 => 
            array (
                'id' => '29',
                'category_id' => '2',
                'name' => 'Rerum atque enim.',
                'image_url' => 'https://lorempixel.com/400/400/?55953',
                'description' => 'Voluptatibus quia rerum aut distinctio in nobis suscipit. Alias et dolores explicabo qui. Voluptas quasi repellat deleniti maxime voluptatem nostrum.',
                'price' => '500',
                'offer' => '0',
                'offer_price' => '6',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
            29 => 
            array (
                'id' => '30',
                'category_id' => '2',
                'name' => 'Dolorem dolorem distinctio.',
                'image_url' => 'https://lorempixel.com/400/400/?32862',
                'description' => 'Illum expedita repellendus rerum optio cumque voluptates eligendi. Culpa doloribus non repellat quas voluptatem perspiciatis consequuntur. Voluptatem autem cumque corrupti dignissimos enim et ut. Voluptates ipsa necessitatibus corrupti laborum ut provident deserunt.',
                'price' => '989',
                'offer' => '0',
                'offer_price' => '5',
                'available' => '1',
                'created_at' => '2020-06-16 17:51:34',
                'updated_at' => '2020-06-16 17:51:34',
            ),
        ));
        
        
    }
}